name: app_icons
description: 772 Phosphor icons for Flutter — thin, light, regular, bold, fill, and duotone styles.
version: 1.0.0
homepage: https://phosphoricons.com
repository: https://github.com/liontude/app-icons

environment:
  sdk: ">=2.13.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: PhosphorBold
      fonts:
        - asset: lib/fonts/Phosphor-Bold.ttf
          weight: 400
    - family: PhosphorDuotone
      fonts:
        - asset: lib/fonts/Phosphor-Duotone.ttf
          weight: 400
    - family: PhosphorFill
      fonts:
        - asset: lib/fonts/Phosphor-Fill.ttf
          weight: 400
    - family: PhosphorLight
      fonts:
        - asset: lib/fonts/Phosphor-Light.ttf
          weight: 400
    - family: PhosphorThin
      fonts:
        - asset: lib/fonts/Phosphor-Thin.ttf
          weight: 400
    - family: PhosphorRegular
      fonts:
        - asset: lib/fonts/Phosphor.ttf
          weight: 400
